defmodule VmuCore.FAS.HSM do
  @moduledoc """
  Behaviour contract for Hardware Security Module operations (FAS-P7 7A).

  All cryptographic card-security operations are delegated to an HSM adapter
  so the authorization pipeline never handles plaintext PINs or key material
  directly. In dev/UAT the `SoftHSM` module fulfills this contract using
  `:crypto`; in production a vendor-specific adapter (Thales, Utimaco, etc.)
  connects via TCP socket or PKCS#11.

  ## Selecting the adapter

      # config/dev.exs
      config :vmu_core, :hsm_adapter, VmuCore.FAS.HSM.SoftHSM

      # config/prod.exs
      config :vmu_core, :hsm_adapter, VmuCore.FAS.HSM.ProductionHSM

  ## CVV variants

  CVV1 (track 2, magstripe), CVV2 (card-not-present / printed), and iCVV
  (dynamic value generated by EMV chip) all use the same 3DES algorithm but
  differ only in the service-code input:
    - CVV1  → actual 3-digit service code from track 2
    - CVV2  → "000"
    - iCVV  → "999"

  `verify_cvv/4` accepts any variant via the `service_code` parameter.
  """

  # ---------------------------------------------------------------------------
  # Behaviour callbacks
  # ---------------------------------------------------------------------------

  @doc """
  Verify a CVV / CVV2 / iCVV value.

  - `pan`          — full PAN (with check digit)
  - `expiry`       — YYMM string from DE14 or track 2
  - `service_code` — "xxx" from track 2 (CVV1) | "000" (CVV2) | "999" (iCVV)
  - `cvv`          — 3-digit CVV value to verify
  """
  @callback verify_cvv(pan :: String.t(), expiry :: String.t(),
                       service_code :: String.t(), cvv :: String.t()) ::
              :ok | {:error, :cvv_mismatch}

  @doc """
  Verify an EMV Application Request Cryptogram (ARQC) from DE55 tag 9F26.

  - `pan_token`       — SHA-256 hex of PAN (for key derivation lookup)
  - `atc`             — Application Transaction Counter from tag 9F36 (2 bytes)
  - `unpredictable_no` — Terminal unpredictable number from tag 9F37 (4 bytes)
  - `txn_data`        — serialised transaction data (amount, currency, date, etc.)
  - `arqc`            — 8-byte ARQC from tag 9F26 to verify
  """
  @callback verify_arqc(pan_token :: String.t(), atc :: binary(),
                        unpredictable_no :: binary(), txn_data :: binary(),
                        arqc :: binary()) ::
              :ok | {:error, :arqc_mismatch} | {:error, :key_not_found}

  @doc """
  Generate an Authorisation Response Cryptogram (ARPC) to include in DE55 of
  the 0110 response. Uses Method 1 (XOR ARQC with ARC, re-encrypt).

  - `arqc` — 8-byte ARQC from the request
  - `arc`  — 2-byte Authorization Response Code (e.g. <<0x00, 0x00>> for "00")
  - `pan_token` — for session key derivation
  """
  @callback generate_arpc(arqc :: binary(), arc :: binary(), pan_token :: String.t()) ::
              {:ok, binary()} | {:error, term()}

  @doc """
  Verify a PIN block from DE52 against the stored PIN hash for the card.

  `pin_block_hex` — hex-encoded ISO 9564 Format-0 PIN block (as received in DE52
  after switch-side ZPK translation — plain PIN block XOR'd with PAN block,
  NOT still encrypted under ZPK).

  Returns:
    `:ok`                   — PIN correct; try counter reset to 0
    `{:error, :wrong_pin}`  — PIN incorrect; try counter incremented
    `{:error, :pin_blocked}` — try counter exceeded max; card PIN locked
    `{:error, :pin_not_set}` — no PIN record found for this pan_token
  """
  @callback verify_pin(pin_block_hex :: String.t(), pan :: String.t(),
                       pan_token :: String.t()) ::
              :ok | {:error, :wrong_pin} | {:error, :pin_blocked} | {:error, :pin_not_set}

  @doc """
  Change the stored PIN for a card, verifying the old PIN first (CTA self-service
  channels — IVR/app/web/ATM).

  Unlike `verify_pin/3`, this takes **plaintext PIN digits** rather than an
  encoded ISO 9564 PIN block: self-service channels only ever know the card's
  `pan_token` (this system never stores or transmits the raw PAN outside a
  live network authorization message), so there is no PAN available to decode
  an ISO block against. The calling channel is responsible for capturing and
  validating PIN digit input; this callback hashes and stores them the same
  way `verify_pin/3` reads them, so a PIN changed here is immediately what
  authorization-time `verify_pin/3` checks against.

  - `pan_token` — SHA-256 hex of PAN (same lookup key `verify_pin/3` uses)
  - `old_pin`   — current plaintext PIN digits, to verify before changing
  - `new_pin`   — new plaintext PIN digits to store

  Returns:
    `:ok`                        — old PIN verified, new PIN stored, try counter reset
    `{:error, :wrong_pin}`       — old PIN incorrect; try counter incremented
    `{:error, :pin_blocked}`     — try counter exceeded max; card PIN locked
    `{:error, :pin_not_set}`     — no PIN record found for this pan_token
    `{:error, :invalid_pin_format}` — new_pin isn't 4-6 numeric digits
  """
  @callback change_pin(pan_token :: String.t(), old_pin :: String.t(), new_pin :: String.t()) ::
              :ok | {:error, :wrong_pin} | {:error, :pin_blocked} | {:error, :pin_not_set} |
              {:error, :invalid_pin_format}

  @doc """
  Build DE55 issuer script TLV for the 0110 response.

  `commands` is a list of atoms describing script actions:
    - `:block_card`       → Script tag 72: put card in terminal capture list
    - `:reset_pin_tries`  → Script tag 71: reset PIN try counter on chip
    - `:update_params`    → Script tag 71: update application parameters
  """
  @callback build_issuer_scripts(pan_token :: String.t(), commands :: [atom()]) ::
              {:ok, binary()} | {:error, term()}

  # ---------------------------------------------------------------------------
  # Delegation helper — resolves adapter from application env
  # ---------------------------------------------------------------------------

  @doc "Returns the configured HSM adapter module."
  @spec adapter() :: module()
  def adapter do
    Application.get_env(:vmu_core, :hsm_adapter, __MODULE__.SoftHSM)
  end

  @doc "Delegates `verify_cvv/4` to the configured adapter."
  def verify_cvv(pan, expiry, service_code, cvv),
    do: adapter().verify_cvv(pan, expiry, service_code, cvv)

  @doc "Delegates `verify_arqc/5` to the configured adapter."
  def verify_arqc(pan_token, atc, un, txn_data, arqc),
    do: adapter().verify_arqc(pan_token, atc, un, txn_data, arqc)

  @doc "Delegates `generate_arpc/3` to the configured adapter."
  def generate_arpc(arqc, arc, pan_token),
    do: adapter().generate_arpc(arqc, arc, pan_token)

  @doc "Delegates `verify_pin/3` to the configured adapter."
  def verify_pin(pin_block_hex, pan, pan_token),
    do: adapter().verify_pin(pin_block_hex, pan, pan_token)

  @doc "Delegates `change_pin/3` to the configured adapter."
  def change_pin(pan_token, old_pin, new_pin),
    do: adapter().change_pin(pan_token, old_pin, new_pin)

  @doc "Delegates `build_issuer_scripts/2` to the configured adapter."
  def build_issuer_scripts(pan_token, commands),
    do: adapter().build_issuer_scripts(pan_token, commands)
end
