defmodule VmuCore.CMS.WalletQrIdentity do
  @moduledoc """
  Digital Wallet Phase W3 (2026-07-28) — personal QR wire format for
  receive/pay. Adapts wallet-app's own real `WalletTransfers.QrIdentity`
  design (confirmed via direct code research, see `docs/wallet/
  DIGITAL_WALLET_Module_Requirements.md` §4) — same shape, decimal
  amounts instead of minor-unit integers (this codebase's own money
  convention throughout, see `CLAUDE.md`: "Always use Decimal for
  monetary values, never float").

  Format: `WAL|v1|<wallet_account_id>|<currency>|<amount>|<label>|<checksum>`

  `<amount>` is empty for an open-amount QR (payer enters the amount at
  pay time — see `WalletQrPaymentCommand`).

  `<checksum>` is a truncated SHA-256 over the other fields. **This
  detects transcription/corruption errors — it is NOT a cryptographic
  signature.** Anyone who can compute SHA-256 can forge a checksum for
  arbitrary field values; it does not prove a QR was genuinely
  generated by this system. Same honest limitation wallet-app's own
  real implementation has (confirmed: no signing key anywhere in its
  `QrIdentity` module either).
  """

  @version "v1"

  @doc """
  Generates a QR wire-format string for `wallet_account_id` to receive
  payment. `amount` may be `nil` for an open-amount QR. `label` is a
  free-text note — pipe/newline characters are stripped for wire-format
  safety (not a security measure, just so `parse/1`'s naive `split("|")`
  can't be confused by a label containing the delimiter).
  """
  @spec generate(Ecto.UUID.t(), String.t(), Decimal.t() | nil, String.t()) :: String.t()
  def generate(wallet_account_id, currency, amount \\ nil, label \\ "") do
    amount_str = if amount, do: Decimal.to_string(amount), else: ""
    safe_label = sanitize(label)

    payload = Enum.join([wallet_account_id, currency, amount_str, safe_label], "|")

    Enum.join(["WAL", @version, wallet_account_id, currency, amount_str, safe_label, checksum(payload)], "|")
  end

  @doc """
  Parses and validates a QR wire-format string. Returns
  `{:ok, %{wallet_account_id:, currency:, amount:, label:}}` or
  `{:error, :invalid_format | :unsupported_version | :checksum_mismatch}`.
  `amount` in the returned map is `nil` for an open-amount QR.
  """
  @spec parse(String.t()) :: {:ok, map()} | {:error, atom()}
  def parse(qr_string) when is_binary(qr_string) do
    case String.split(qr_string, "|") do
      ["WAL", @version, wallet_account_id, currency, amount_str, label, checksum] ->
        payload = Enum.join([wallet_account_id, currency, amount_str, label], "|")

        if checksum(payload) == checksum do
          {:ok, %{
            wallet_account_id: wallet_account_id,
            currency: currency,
            amount: parse_amount(amount_str),
            label: label
          }}
        else
          {:error, :checksum_mismatch}
        end

      ["WAL", _other_version | _] ->
        {:error, :unsupported_version}

      _ ->
        {:error, :invalid_format}
    end
  end
  def parse(_), do: {:error, :invalid_format}

  defp checksum(payload) do
    :crypto.hash(:sha256, payload) |> Base.encode16(case: :lower) |> String.slice(0, 16)
  end

  defp parse_amount(""), do: nil
  defp parse_amount(str) do
    case Decimal.parse(str) do
      {d, ""} -> d
      _ -> nil
    end
  end

  defp sanitize(label) do
    label
    |> to_string()
    |> String.replace("|", "")
    |> String.replace("\n", " ")
    |> String.slice(0, 60)
  end
end
